
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - model_service

  frontend:
    image: ghcr.io/tsaqifradhitya/trustchain-frontend:latest
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=/api/v1
    ports:
      - "5173:5173"
  backend:
    image: ghcr.io/tsaqifradhitya/trustchain-auth-service:latest
    build:
      context: ./backend/auth_service
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_service
      - DB_SSLMODE=disable
      - JWT_SECRET=my-super-secret-key-12345
      - JWT_REFRESH_SECRET=my-super-secret-refresh-key-67890
    depends_on:
      - db

  model_service:
    image: ghcr.io/tsaqifradhitya/trustchain-model-service:latest
    build:
      context: ./backend/model_service
    environment:
      - PORT=8000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8001:8000"
        
    volumes:
      - ./backend/model_service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dummy_api:
    image: ghcr.io/tsaqifradhitya/trustchain-dummy-api:latest
    build:
      context: ./backend/dummy_api

  explorer_service:
    image: ghcr.io/tsaqifradhitya/trustchain-explorer-service:latest
    build:
      context: ./backend/explorer_service
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_service
      - DB_SSLMODE=disable
      - ERP_API_URL=http://dummy_api:8080/predict
      - MODEL_API_URL=http://model_service:8000/predict
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      db:
        condition: service_started
      dummy_api:
        condition: service_started
      model_service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata:
